# Generated by Django 4.2.7 on 2025-09-26 22:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceTypingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('language', models.CharField(choices=[('en-US', 'English (US)'), ('en-GB', 'English (UK)'), ('es-ES', 'Spanish (Spain)'), ('es-MX', 'Spanish (Mexico)'), ('fr-FR', 'French (France)'), ('de-DE', 'German'), ('it-IT', 'Italian'), ('pt-BR', 'Portuguese (Brazil)'), ('ja-JP', 'Japanese'), ('ko-KR', 'Korean'), ('zh-CN', 'Chinese (Simplified)'), ('zh-TW', 'Chinese (Traditional)')], default='en-US', max_length=10)),
                ('text_to_speak', models.TextField()),
                ('expected_words', models.JSONField(default=list, help_text='Expected words for pronunciation check')),
                ('pronunciation_hints', models.TextField(blank=True)),
                ('target_wpm', models.PositiveIntegerField(default=20)),
                ('target_accuracy', models.PositiveIntegerField(default=80)),
                ('target_pronunciation', models.FloatField(default=0.8)),
                ('time_limit_minutes', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_voice_exercises', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'verbose_name': 'Voice Typing Exercise',
                'verbose_name_plural': 'Voice Typing Exercises',
                'db_table': 'voice_typing_exercises',
                'ordering': ['difficulty', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VoiceTypingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('en-US', 'English (US)'), ('en-GB', 'English (UK)'), ('es-ES', 'Spanish (Spain)'), ('es-MX', 'Spanish (Mexico)'), ('fr-FR', 'French (France)'), ('de-DE', 'German'), ('it-IT', 'Italian'), ('pt-BR', 'Portuguese (Brazil)'), ('ja-JP', 'Japanese'), ('ko-KR', 'Korean'), ('zh-CN', 'Chinese (Simplified)'), ('zh-TW', 'Chinese (Traditional)')], default='en-US', max_length=10)),
                ('voice_speed', models.FloatField(default=1.0, help_text='Speech rate (0.5-2.0)')),
                ('voice_pitch', models.FloatField(default=1.0, help_text='Voice pitch (0.5-2.0)')),
                ('auto_punctuation', models.BooleanField(default=True)),
                ('profanity_filter', models.BooleanField(default=True)),
                ('confidence_threshold', models.FloatField(default=0.7, help_text='Minimum confidence for recognition')),
                ('show_confidence_scores', models.BooleanField(default=True)),
                ('show_pronunciation_hints', models.BooleanField(default=True)),
                ('audio_feedback', models.BooleanField(default=True)),
                ('practice_mode', models.BooleanField(default=True)),
                ('repeat_exercises', models.BooleanField(default=False)),
                ('adaptive_difficulty', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Typing Settings',
                'verbose_name_plural': 'Voice Typing Settings',
                'db_table': 'voice_typing_settings',
            },
        ),
        migrations.CreateModel(
            name='VoiceTypingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en-US', 'English (US)'), ('en-GB', 'English (UK)'), ('es-ES', 'Spanish (Spain)'), ('es-MX', 'Spanish (Mexico)'), ('fr-FR', 'French (France)'), ('de-DE', 'German'), ('it-IT', 'Italian'), ('pt-BR', 'Portuguese (Brazil)'), ('ja-JP', 'Japanese'), ('ko-KR', 'Korean'), ('zh-CN', 'Chinese (Simplified)'), ('zh-TW', 'Chinese (Traditional)')], default='en-US', max_length=10)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_typing/audio/')),
                ('transcript', models.TextField()),
                ('confidence_score', models.FloatField(help_text='Speech recognition confidence (0-1)')),
                ('words_spoken', models.PositiveIntegerField()),
                ('words_per_minute', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('pronunciation_score', models.FloatField(blank=True, null=True)),
                ('mispronounced_words', models.JSONField(blank=True, default=list)),
                ('unclear_segments', models.JSONField(blank=True, default=list)),
                ('suggested_improvements', models.TextField(blank=True)),
                ('duration', models.DurationField()),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Typing Session',
                'verbose_name_plural': 'Voice Typing Sessions',
                'db_table': 'voice_typing_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PronunciationGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('en-US', 'English (US)'), ('en-GB', 'English (UK)'), ('es-ES', 'Spanish (Spain)'), ('es-MX', 'Spanish (Mexico)'), ('fr-FR', 'French (France)'), ('de-DE', 'German'), ('it-IT', 'Italian'), ('pt-BR', 'Portuguese (Brazil)'), ('ja-JP', 'Japanese'), ('ko-KR', 'Korean'), ('zh-CN', 'Chinese (Simplified)'), ('zh-TW', 'Chinese (Traditional)')], default='en-US', max_length=10)),
                ('phonetic_spelling', models.CharField(max_length=200)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_typing/pronunciation/')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('common_mispronunciations', models.JSONField(blank=True, default=list)),
                ('tips', models.TextField(blank=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pronunciation Guide',
                'verbose_name_plural': 'Pronunciation Guides',
                'db_table': 'pronunciation_guides',
                'ordering': ['word'],
                'unique_together': {('word', 'language')},
            },
        ),
        migrations.CreateModel(
            name='VoiceTypingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('best_wpm', models.FloatField(default=0.0)),
                ('best_accuracy', models.FloatField(default=0.0)),
                ('best_pronunciation', models.FloatField(default=0.0)),
                ('total_time', models.DurationField(default=datetime.timedelta(0))),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mastery_level', models.CharField(default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempted', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='voice_typing.voicetypingexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Typing Progress',
                'verbose_name_plural': 'Voice Typing Progress',
                'db_table': 'voice_typing_progress',
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
